name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    name: ${{ matrix.os }}, py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["310", "314"]
        include:
          - os: macos-latest
            python-version: "314"
    env:
      PIXI_ENV_NAME: test-py${{ matrix.python-version }}
      CONDA_NOTIFY_OUTDATED_CONDA: "false"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
        with:
          environments: ${{ env.PIXI_ENV_NAME }}
      - name: Run checks
        run: pixi run --environment ${{ env.PIXI_ENV_NAME }} check

  build:
    name: Build conda package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
        with:
          environments: build
      - name: Build package
        run: pixi run --environment build build
